### ISSUE TITLE
Crash on restoring state

### ISSUE THREAD

**Issue by andriydruk** [AetherQuinque/ReactiveMvvm#1]
1. Switch on  "Don't keep activities" 
2. Run application
3. Home button
4. Return to app

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quinque.aether.reactivemvvm/com.quinque.aether.reactivemvvm.MainActivity}: java.lang.ClassCastException: com.quinque.aether.reactivemvvm.base.BaseViewModel cannot be cast to com.quinque.aether.reactivemvvm.ViewModel
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
     at android.app.ActivityThread.-wrap12(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:154)
     at android.app.ActivityThread.main(ActivityThread.java:6121)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.ClassCastException: com.quinque.aether.reactivemvvm.base.BaseViewModel cannot be cast to com.quinque.aether.reactivemvvm.ViewModel
     at com.quinque.aether.reactivemvvm.MainActivity.onCreate(MainActivity.java:17)
     at android.app.Activity.performCreate(Activity.java:6682)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:154) 
     at android.app.ActivityThread.main(ActivityThread.java:6121) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

**Comment by AetherQuinque** [comment]
Thanks for your help!) I have just fixed and committed the changes. It should work now.
